name: GitHub Action Slack Notify CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Notify slack
        # Don't attempt to send Slack notifications on fork PRs which don't have access to secrets
        if: env.SLACK_BOT_TOKEN
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: ./
        with:
          channel_id: '#gha-testing'
          status: STARTED
          color: good
      - name: npm install, build and test
        run: |
          npm ci
          npm run build
          npm run test
        env:
          CI: true
      - name: Notify slack success
        if: env.SLACK_BOT_TOKEN
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: ./
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: '#gha-testing'
          status: SUCCESS
          color: good
